# .travis.yml
branches:
    only:
        - master

language: node_js

before_install:
    - npm install -g grunt-cli

before_script:
    - npm install grunt-contrib-jasmine

script:
    - grunt travis --verbose"